apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: hello-task
spec:
  steps:
    - name: echo
      image: ubuntu
      command:
        - echo
      args:
        - "hello world"
    - name: echo2
      image: ubuntu
      command:
        - echo
      args:
        - "This is tekton-pipeline template, yahooo!"
